name: nbex-build
channels:
  - defaults
  - conda-forge
  - pytorch
  - mhoelzl
  # - fastai
dependencies:
  - python>=3.8
  - pip>=20.2.4
  # - altair
  - anaconda-client
  # - autoflake
  - black
  - bump2version>=1.0.1
  # - catboost
  - conda-build>=3.21
  - conda-verify
  - click>=7.1.2
  - coverage>=5.3
  # - dask
  # - fastai  # activate fastai channel above!
  - flake8>=3.8.4
  - ipython>=6.0
  # - jupyterlab
  # - keras
  # - lightgbm
  # - matplotlib
  # - nbdime
  # - nbex
  # - nbstripout
  # - neo4j-python-driver
  # - numpy
  # - optuna
  # - owlready2
  # - pandas
  # - pre_commit
  # - pytest-cov
  - pytest-runner>=5.2
  - pytest>=6.1.2
  # - pytorch
  # - rdflib
  # - recommonmark
  # - rope
  # - scikit-learn
  # - scipy
  # - seaborn
  # - sktime
  # - spacy
  - sphinx>=3.3.0
  # - statsmodels
  # - tensorflow
  - tox>=3.20.1
  # - tqdm
  # - tslearn
  - twine>=3.4.1
  - watchdog>=0.9.0
  - wheel>=0.35.1
  # - xgboost
  # - yellowbrick

  - pip:
    #  - -e .  # install git checkout of br_kg in editable mode
    # add here only pip-packages that are not available in conda/conda-forge! E.g.:
    # - icecream
    # - jax
    # - numpyro
    # - funsor
    # - neptune-client
    # - neptune-contrib
