{% set name = "nbex" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: v0.4.0
  git_url: https://github.com/hoelzl/nbex.git

build:
  noarch: python
  number: 2
  entry_points:
    - nbex=nbex.cli:main
  ignore_run_exports:
    - click
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - click >=7.1.2
    - ipython >=6.0
    - numpy >=1.16
    - pip
    - python
    - pytest-runner >=5.2
  run:
    - click >=7.1.2
    - numpy >=1.16
    - python

test:
  imports:
    - nbex
  commands:
    - nbex --help
  requires:
    - pytest >=3.8

about:
  home: "https://github.com/hoelzl/nbex"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Support for code that works interactively and in batch mode."
  doc_url: https://nbex.readthedocs.io
  dev_url: https://github.com/hoelzl/nbex

extra:
  recipe-maintainers:
    - hoelzl
